name: Hello World! with checkout

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet
        run: |
          echo "Hello World!"
      - run: echo "Hello World! again..."
      - run: date
      - run: ls -l
